version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1.4
    working_directory: ~/contracts
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            yarn
            yarn truffle install
      - run:
          name: test
          command: yarn test:all